import type { Metadata } from 'next'
import Link from 'next/link'
import type { ReactNode } from 'react'
import index from '../../.generated/component-index.json'
import { Code } from '../../components/code-block'

export const metadata: Metadata = {
  title: 'English',
  description:
    'Novi UI in English: one core on React Aria Components, several themes that change the DOM structure, not just the colours.',
}

const CONTRACTS = index.components.length
const COLORS = Object.values(index.themes)[0]?.colorSet.length ?? 0

const INSTALL = 'pnpm add @novi-ui/core @novi-ui/raster react-aria-components'

const SETUP = `/* app/globals.css */
@import "tailwindcss";
@import "@novi-ui/core/base.css";
@import "@novi-ui/raster/raster.css";

/* let Tailwind see the classes the theme emits — path is relative to this CSS file */
@source "../node_modules/@novi-ui/raster/dist";`

const USAGE = `import { Button, Input } from '@novi-ui/raster'

export function SignInForm() {
  return (
    <form>
      <Input label="Email" type="email" isRequired />
      <Button type="submit" color="primary">Send</Button>
    </form>
  )
}`

const ATTRIBUTES = `<html data-novi-theme="raster" data-novi-scheme="dark" data-novi-color="brick">`

const THEMES = [
  {
    pkg: '@novi-ui/raster',
    label: 'Raster',
    aesthetic: 'Minimal, Swiss grid',
    modal: 'Floats in the centre over a dimmed backdrop. Close is an ✕ at the top right',
  },
  {
    pkg: '@novi-ui/tactile',
    label: 'Tactile',
    aesthetic: 'Touch-first, larger surfaces',
    modal: 'Rises from the bottom as a sheet. Close is full-width in the footer',
  },
  {
    pkg: '@novi-ui/flatlay',
    label: 'Flatlay',
    aesthetic: 'No z-axis, paper and ruled lines',
    modal: 'Replaces the page as a full takeover. Close is “← back” at the top left',
  },
] as const

function H2({ children }: { children: string }) {
  return <h2 className="text-2xl font-medium tracking-[-0.015em]">{children}</h2>
}

function P({ children }: { children: ReactNode }) {
  return <p className="max-w-[40em] text-base leading-[1.8] text-site-muted">{children}</p>
}

function Strong({ children }: { children: ReactNode }) {
  return <strong className="font-medium text-site-fg">{children}</strong>
}

export default function EnglishPage() {
  return (
    <article lang="en" className="flex max-w-3xl flex-col gap-[clamp(2.5rem,6vw,4rem)]">
      <header className="flex flex-col gap-3">
        <h1 className="text-balance text-[clamp(2rem,5vw,3rem)] font-medium leading-[1.15] tracking-[-0.02em]">
          One core, several aesthetics
        </h1>
        <P>
          Novi UI is a React component library built on React Aria Components.{' '}
          <code className="font-mono text-[0.9em]">@novi-ui/core</code> owns behaviour,
          accessibility and the type contracts. Theme packages own structure and style only, so
          switching themes changes <Strong>how the DOM is assembled</Strong>, not just the colours
          and corner radii.
        </P>
        <P>
          <Strong>The rest of this site is in Japanese.</Strong> This page covers everything you
          need to install and use the library; for AI agents there is a machine-readable English
          summary at{' '}
          <a href="/llms-en.txt" className="underline underline-offset-4">
            llms-en.txt
          </a>
          .
        </P>
      </header>

      <section className="flex flex-col gap-4">
        <H2>Three themes, one API</H2>
        <P>
          All three implement the same {CONTRACTS} contracts and expose an identical public API. The
          same <code className="font-mono text-[0.9em]">{'<Modal>'}</code> becomes three different
          structures:
        </P>
        <dl className="flex flex-col gap-4">
          {THEMES.map((t) => (
            <div key={t.pkg} className="flex flex-col gap-1 border-t border-site-border pt-3">
              <dt className="flex flex-wrap items-baseline gap-x-3">
                <span className="font-medium">{t.label}</span>
                <code className="font-mono text-sm text-site-muted">{t.pkg}</code>
                <span className="text-sm text-site-muted">{t.aesthetic}</span>
              </dt>
              <dd className="max-w-[40em] text-sm leading-[1.7] text-site-muted">{t.modal}</dd>
            </div>
          ))}
        </dl>
        <P>
          You can see all three side by side on the{' '}
          <Link href="/" className="underline underline-offset-4">
            home page
          </Link>
          .
        </P>
      </section>

      <section className="flex flex-col gap-4">
        <H2>Install</H2>
        <P>
          <Strong>Requires React 19 and Tailwind CSS v4.</Strong> A theme&rsquo;s CSS ships token
          definitions only; the component classes are generated by your Tailwind. Without Tailwind
          and the <code className="font-mono text-[0.9em]">@source</code> line, nothing renders.
        </P>
        <Code>{INSTALL}</Code>
        <Code>{SETUP}</Code>
        <Code>{USAGE}</Code>
        <P>
          No provider is required. Prop names follow React Aria:{' '}
          <code className="font-mono text-[0.9em]">isDisabled</code> rather than{' '}
          <code className="font-mono text-[0.9em]">disabled</code>,{' '}
          <code className="font-mono text-[0.9em]">onPress</code> rather than{' '}
          <code className="font-mono text-[0.9em]">onClick</code>.
        </P>
      </section>

      <section className="flex flex-col gap-4">
        <H2>Theme, scheme and colourway</H2>
        <P>Everything is an attribute on the root element, and all of them are optional.</P>
        <Code>{ATTRIBUTES}</Code>
        <ul className="flex max-w-[40em] list-disc flex-col gap-2 pl-5 text-base leading-[1.8] text-site-muted">
          <li>
            <code className="font-mono text-[0.9em]">data-novi-theme</code> — omit it when you
            import a single theme&rsquo;s CSS. Use the{' '}
            <code className="font-mono text-[0.9em]">.scoped.css</code> build to run several themes
            on one page
          </li>
          <li>
            <code className="font-mono text-[0.9em]">data-novi-scheme</code> —{' '}
            <code className="font-mono text-[0.9em]">light</code> or{' '}
            <code className="font-mono text-[0.9em]">dark</code>. Omit it to follow the OS setting
          </li>
          <li>
            <code className="font-mono text-[0.9em]">data-novi-color</code> — each theme owns{' '}
            {COLORS} colours and <Strong>the names differ per theme</Strong>. An unknown name falls
            back to that theme&rsquo;s default. See the{' '}
            <Link href="/docs/lookbook/" className="underline underline-offset-4">
              Lookbook
            </Link>
          </li>
        </ul>
      </section>

      <section className="flex flex-col gap-4">
        <H2>What is not here yet</H2>
        <P>
          Table, ComboBox, DatePicker, Pagination, Slider and NumberField are not implemented. React
          Aria provides the behaviour for all of them, so they are next, but if you need them today
          another library will be faster. The version is 0.x and the API will change.
        </P>
      </section>

      <section className="flex flex-col gap-4">
        <H2>Links</H2>
        <ul className="flex flex-col gap-2 text-sm">
          <li>
            <a
              href="https://github.com/yuuto22009911-hash/novi"
              className="text-site-accent underline underline-offset-4"
            >
              GitHub
            </a>{' '}
            <span className="text-site-muted">— source, English README, MIT</span>
          </li>
          <li>
            <a
              href="https://www.npmjs.com/package/@novi-ui/core"
              className="text-site-accent underline underline-offset-4"
            >
              npm
            </a>{' '}
            <span className="text-site-muted">— @novi-ui/core, raster, tactile, flatlay, mcp</span>
          </li>
          <li>
            <a href="/llms-en.txt" className="text-site-accent underline underline-offset-4">
              llms-en.txt
            </a>{' '}
            <span className="text-site-muted">— English summary for AI agents</span>
          </li>
          <li>
            <Link
              href="/docs/components/button/"
              className="text-site-accent underline underline-offset-4"
            >
              Component reference
            </Link>{' '}
            <span className="text-site-muted">— props tables and live demos (Japanese)</span>
          </li>
        </ul>
      </section>
    </article>
  )
}
